In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[4, 27]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[14, 21], [4, 27], [12, 25], [2, 19, 11], [22, 3, 24], [28, 21], [7, 3, 19], [6, 7], [6, 11], [15, 7]]


In [6]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[14 21  0]
 [ 4 27  0]
 [12 25  0]
 [ 2 19 11]
 [22  3 24]
 [28 21  0]
 [ 7  3 19]
 [ 6  7  0]
 [ 6 11  0]
 [15  7  0]]


In [7]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [8]:
X = padded_reviews
y = sentiment

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
model.fit(X, y, epochs=50, verbose=0)

In [11]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 414ms/step - loss: 0.6389 - accuracy: 1.0000


1.0

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [14]:
weights[14]

array([0.03126436, 0.06365734, 0.10016003, 0.0431118 ], dtype=float32)

In [15]:
weights[25]

array([7.8711383e-02, 3.9708607e-02, 6.7306124e-02, 3.3434364e-05],
      dtype=float32)